### Array

##### ---------------------------------------------------基本觀念釐清-------------------------------------------------

##### 陣列跟矩陣到底有什麼不同？首先，陣列(array)依照其維度可分成一維、二維與多維。

##### 若陣列只有一維，我們通常稱它為向量(vector)，例如：[1, 2, 3]。

##### 若陣列為二維且每一列長度皆相同，我們就會稱它為矩陣(matrix)，例如：[[1, 2, 3], [4, 5, 6]]。

##### ----------------------------------------------------------------------------------------------------------------------

### 如何建置array

In [38]:
import numpy as np
A1 = np.array([[1, 2], [3, 4]])
print "array的data為 ： ","\n",(A1)
print "array的type為 ： ", type(A1)
A2 = np.matrix([[1, 2], [3, 4]])
print "matrix的data為 ： ","\n",(A2)
print "matrix的type為 ： ", type(A2)
print "================================================"
A = np.matrix([[ 1, 2, 3], [ 3, 4, 5], [ 5, 6, 7]])
print "matrix的data為 ： ","\n",A
print "matrix的type為 ： ",type(A)
print "matrix.A的維度為 ： ", np.ndim(A)
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print "array的data為 ： ","\n",A
print "array的type為 ： ",type(A)
print "array.A的維度為 ： ", np.ndim(A)

array的data為 ：  
[[1 2]
 [3 4]]
array的type為 ：  <type 'numpy.ndarray'>
matrix的data為 ：  
[[1 2]
 [3 4]]
matrix的type為 ：  <class 'numpy.matrixlib.defmatrix.matrix'>
matrix的data為 ：  
[[1 2 3]
 [3 4 5]
 [5 6 7]]
matrix的type為 ：  <class 'numpy.matrixlib.defmatrix.matrix'>
matrix.A的維度為 ：  2
array的data為 ：  
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
array的type為 ：  <type 'numpy.ndarray'>
array.A的維度為 ：  3


In [16]:
#coding:UTF-8
from sklearn import datasets
iris = datasets.load_iris()
print iris.get("data")[1:5],"\n"
print "iris.data的type為 ： ","\n", type(iris.data),"\n"
print "iris.data的data為 ： ","\n", iris.data[1:5],"\n"
print "iris.target的type為 ： ","\n",type(iris.target),"\n"
print "iris.target的data為 ： ","\n", iris.target[1:5],"\n"

[[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]] 

iris.data的type為 ：  
<type 'numpy.ndarray'> 

iris.data的data為 ：  
[[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]] 

iris.target的type為 ：  
<type 'numpy.ndarray'> 

iris.target的data為 ：  
[0 0 0 0] 



In [2]:
import numpy as np
a = [["123","321","456"]]
b = np.array(a)
print type(b)

<type 'numpy.ndarray'>


In [21]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
print X
print type(X)
y = np.array([1, 2, 3, 4, 5, 6])
# print y
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)
# MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
# print(clf.predict(X[2:3]))

[[3 0 1 1 3 1 3 2 1 2 4 2 4 2 4 0 2 2 4 2 1 2 2 1 1 4 3 4 4 3 4 2 4 2 1 4 1
  4 1 0 2 3 4 1 2 3 2 0 3 4 2 2 2 0 4 2 4 4 3 0 3 2 4 4 0 4 0 0 0 3 1 3 2 4
  3 0 4 0 1 3 2 0 2 2 1 0 2 1 4 2 2 4 1 0 3 0 4 1 3 3]
 [0 3 0 0 3 1 1 3 0 2 4 4 1 0 0 0 2 3 3 1 4 2 1 0 1 2 3 3 2 1 1 1 1 1 1 2 2
  1 1 2 2 4 0 4 4 1 0 0 0 1 4 0 0 0 0 4 1 4 1 1 0 3 4 4 0 0 1 4 3 3 3 0 1 4
  3 1 2 1 3 3 4 2 4 2 4 1 3 2 3 4 2 4 2 3 3 4 1 0 1 0]
 [0 3 4 1 2 4 1 4 3 2 0 2 0 1 3 2 2 4 3 4 0 3 0 2 0 1 2 3 2 4 0 4 1 2 1 4 0
  4 1 1 2 0 4 2 2 0 4 1 3 1 3 2 3 2 2 2 3 3 2 2 1 3 0 0 4 4 1 3 1 0 2 4 1 0
  0 0 1 3 2 1 1 4 3 3 4 0 1 1 0 3 1 0 3 0 0 4 1 0 3 3]
 [0 3 2 3 1 0 2 2 4 0 3 4 3 4 2 2 2 3 1 1 2 0 3 0 0 1 0 4 3 2 1 0 1 1 0 0 3
  0 0 1 3 3 0 0 0 4 1 3 0 0 1 3 0 3 1 0 0 3 3 3 0 2 4 2 3 0 3 3 0 4 1 4 0 0
  1 1 1 0 0 0 3 3 2 0 1 1 4 4 2 0 1 3 1 0 4 2 4 2 4 4]
 [1 3 0 1 0 1 1 0 0 3 3 0 0 4 0 0 4 2 2 0 4 2 1 3 0 3 2 4 3 4 1 0 2 3 1 0 1
  0 1 3 4 0 1 0 4 4 3 3 2 2 0 1 1 2 3 2 4 2 3 4 1 3 1 1 0 4 0 4 3 3 3 1 2 4
  1 0 4 1 0 0 1 1 1 

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)